FROM apache/airflow:2.9.0-python3.12

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-google==10.13.0 \
    google-cloud-bigquery==3.17.0 \
    dbt-core==1.9.0 \
    dbt-bigquery==1.9.0 \
    astronomer-cosmos \
    faker==22.0.0 \
    pandas==2.2.0 \
    pyarrow==15.0.0