x-airflow-common: &airflow-common
  env_file: .env
  build:
    context: .
    dockerfile: Dockerfile.airflow
  volumes:
    - ~/.config/gcloud/application_default_credentials.json:/opt/airflow/adc.json:ro

services:
  api:
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/app/adc.json:ro

  nginx:
    profiles: ["disabled"]