data_engineering_platform:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "data-pipeline-490114"
      location: EU
      threads: 4
      dataset: raw
      timeout_seconds: 300